### PR TITLE
:sparkles: browse API

### PR DESCRIPTION
**Pull request by fabienjuif**

### CODE REVIEW

**Review by bpetetot — COMMENTED** [review]
Great ! And very clean code ;)

It may be better to have more information about each item : 
 - if it's a directory or not
 - the file extension
 - ...

And the default `/api/fs` may should start where the command line is executed ?

**Comment by bpetetot** [comment]
Does not take into account the second point, I understood why you did like this 😄

**Comment by fabienjuif** [comment]
I don't understand the first point : 
 - you should have the file extension
 - you know this is a directory because I added a "/" at the end when it is

**Comment by bpetetot** [comment]
To avoid parsing on client side of '/' and extensions... it's just confort

**Review by bpetetot — DISMISSED** [review]

**Comment by fabienjuif** [comment]
Exemple of return : 
```json
[
  {
    "fullname": "defaultProps.results.png",
    "name": "defaultProps.results",
    "ext": ".png",
    "isDirectory": false,
    "dev": 16777219,
    "mode": 33188,
    "nlink": 1,
    "uid": 501,
    "gid": 20,
    "rdev": 0,
    "blksize": 4096,
    "ino": 2994337,
    "size": 39340,
    "blocks": 80,
    "atime": "2017-04-24T09:50:59.000Z",
    "mtime": "2017-04-15T08:39:08.000Z",
    "ctime": "2017-04-15T08:39:08.000Z",
    "birthtime": "2017-04-15T08:39:08.000Z"
  }
]
```

**Review by bpetetot — APPROVED** [review]
👍 Yes ;)

**Pull request merged**
